### PR TITLE
Add RGB sliders for ColorTint effect

### PR DESCRIPTION
**Pull request by justynaipham**

### CODE REVIEW

**Review by brollin — COMMENTED** [review]
I'm liking the idea behind this, but there's an issue: this is basically a breaking change to the color tint effect, and it's already in use in different saved experiences. (You can see that by running `yarn downloadCloudAssets` which will download all of the experiences/audio, then check inside `public/cloud-assets/conjurer-experiences/*.json`)

Maybe we can just make a new effect called ColorTintRGB?

**Comment by brollin** [comment]
Alternatively if we want to add parameter controls for Color parameters, we could do that so that you can change it in the pattern playground.

**Comment by justynaipham** [comment]
Oh dang, backwards compatibility! I'll sit with these thoughts a bit, and consider the possibility of adding additional Pattern param controls. Maybe in conjunction with ints, bools, and min/max settings.

**Comment by brollin** [comment]
Actually this has me motivated to figure that out - I think I will take on the color parameter control. Maybe also the palette parameter control. 

> Maybe in conjunction with ints, bools, and min/max settings.

I like the idea of a bool! From the other PR, maybe that could be implemented like this:
```
    u_boolean_example: {
      name: "Boolean Example",
      value: 1,
      min: 0,
      max: 1,
      step: 1
    },
```

The main upside here being that it can remain a number (you can't pass bools into shaders as uniforms I don't think) and the schema is the same between it and numeric uniforms. Then the ui can just notice that it is a bool and do something special.

**Comment by justynaipham** [comment]
Closing due to breaking changes to saved experiences.

**Pull request closed without merging**
